### PR TITLE
:construction_worker: :construction_worker:

### PR DESCRIPTION
**Pull request by thomas-kl1**
This PR:

- Fix the default icon value to the json encoded value, so the value is correctly processed when the default one is being used
- Remove deprecated usage of `Magento\Framework\App\Action\Action`
- Usage of private over protected
- Usage of composition over inheritance
- Add stricter and proper types to methods
- Split the configuration of snowflage and openweather
- Remove custom block in favor of viewModel that is lighter and reusable
- Add dependencies to the composer.json
- Add the missing ACLs used in settings.xml
- Add "canRestore" attribute in system.xml in order to be able to restore default system values
- Add missing translatable comments in system.xml
- Encrypt API Key for security purpose
- Allows to override the ipconfig url as a config value
- Allows to override the meteo route action url from the layout directly
- Add screenshots of the module in action

### CODE REVIEW

**Comment by mehdichaouch** [comment]
`Module/Config/Snowflake.php`
**Module** :arrow_left: :thinking:

**Comment by mehdichaouch** [comment]
`v1.0.0` is done !
giphy
 I let you check if you want to push fixes.

**Comment by thomas-kl1** [comment]
@mehdichaouch did you meant "I you want to push bugs."? :stuck_out_tongue_closed_eyes:

**Comment by mehdichaouch** [comment]
oula beaucoup de modifs structurelles !
@thomas-kl1 tu as bien testé en local :laughing: , tu as mis de la neige sur sa.lo.mon ?

**Comment by thomas-kl1** [comment]
@mehdichaouch j'ai bien de la :snowflake: !

**Review by mehdichaouch — APPROVED** [review]

**Pull request merged**
